### ISSUE TITLE
Do not show progress bar if knitting

### ISSUE THREAD

**Issue by zeehio** [psolymos/pbapply#15]
When a document is being rendered with knitr, `is.null(getOption("knitr.in.progress"))` will be `FALSE`.

Is it possible to use that option so *by default* the progress bar is not shown when knitting a document, even if the knitting is done from an interactive console? I would think that is the usual expected behaviour.

This is how is being done in the dplyr package:

https://github.com/hadley/dplyr/blob/6153e136fa9397e88478fa6270d9d1f02eb5153e/R/progress.R#L96

Even if it is not possible, thanks for your work

**Comment by psolymos** [comment]
pbapply does not currently check knitr options, but I guess it could. The interactive mode is checked in `zzz.R` during `.onLoad`. Checking knitr option would not impose dependency, so it is a good suggestion. 

I actually did not want the progress bar shown when knitting, because it prints a line for every update. But if you want it back, it is certainly doable in one way or another. You can turn on the progress bar with `pboptions(type="timer")` for example.

**Comment by psolymos** [comment]
I re-read your comment. OK, makes sense. You do not want the pb shown even when it is interactively running through knitr.  It should be an easy fix, will need some testing.

**Comment by psolymos** [comment]
Now it works as expected, see example at the end of the `tests.R` file [here](https://github.com/psolymos/pbapply/blob/master/tests/tests.R).
