### ISSUE TITLE
Feature request: allow mclapply/parLapply options to be set when calling pblapply()

### ISSUE THREAD

**Issue by fcampelo** [psolymos/pbapply#42]
Hi,

First of all, thanks for the awesome package. :-)

Is there a reason why the options of the underlying functions called by _pblapply_ (e.g., _mclapply_) are not available for the user? I'm particularly interested in being able to set _mc.preschedule_ (I'm running processes with very heterogeneous loads). I can give it a try and send a PR later, but I thought I would ask first. ;-)

All the best,

**Comment by psolymos** [comment]
@fcampelo thanks for the request. There is an [option](https://github.com/psolymos/pbapply/blob/72f9e56241549b3efacdd206a24f2258b15a6d49/R/zzz.R#L13) called `use_lb` for which the docs says _Switch for using load balancing when running in parallel clusters. The default value is `FALSE`_. The option is used because it switches the `parLapply` and `parLapplyLB` functions.

Besides this, the `pblapply` function [passes arguments](https://github.com/psolymos/pbapply/blob/72f9e56241549b3efacdd206a24f2258b15a6d49/R/pblapply.R#L41-L71) through `...` to `pbLapply*` and `mclapply` depending on the `cl` argument (cluster or integer). This means that you can pass any argument you like except `cl` and `mc.cores`. 

In your case, `pbapply(..., mc.preschedule=FALSE)` should work.

Hope this helps.

**Comment by fcampelo** [comment]
Hi @psolymos , thanks a lot for the clarification! I wasn't aware of the `use_lb` option, my bad. :-)

The documentation of `pblapply` mentions that the `...` arguments are passed to FUN, but doesn't mention them being passed to `mclapply` as well, which is what confused me. In hindsight I probably should have checked the source code more carefully before opening the issue. ;-)

All the best, and thanks again for the great package!

**Comment by psolymos** [comment]
Added some explanation for future reference. Thanks @fcampelo for flagging it!
